/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

export interface KickoutLogoutRequest {
  userId: string;
}

export interface KickoutKickoutRequest {
  userId: string;
}
