/* eslint-disable */

/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

export interface User {
  id?: string;
  username?: string;
  nickname?: string;
  status?: boolean;
  /** @format date-time */
  createTime?: string;
  /** @format date-time */
  lastUpdateTime?: string;
  /** @format date-time */
  loginTime?: string;
  note?: string;
}

export interface BaseResponseString {
  /** @format int32 */
  code?: number;
  message?: string;
  data?: string;
}

export interface UserLoginDto {
  username?: string;
  publicKey?: string;
  password?: string;
}

export interface UserRegisterDto {
  id?: string;
  username?: string;
  publicKey?: string;
  password?: string;
  nickname?: string;
  status?: boolean;
  /** @format date-time */
  createTime?: string;
  /** @format date-time */
  lastUpdateTime?: string;
  note?: string;
}

export interface RoleRelationDto {
  userId?: string;
  roleIds?: string[];
}

export interface FindPageDto {
  keyword?: string;
  /** @format int32 */
  pageSize?: number;
  /** @format int32 */
  pageNum?: number;
}

export interface BaseResponseObject {
  /** @format int32 */
  code?: number;
  message?: string;
  data?: object;
}

export interface BaseResponseUser {
  /** @format int32 */
  code?: number;
  message?: string;
  data?: User;
}

export interface BaseResponseListRole {
  /** @format int32 */
  code?: number;
  message?: string;
  data?: Role[];
}

export interface Role {
  id?: string;
  name?: string;
  description?: string;
  /** @format int32 */
  status?: number;
}

export interface SearchSessionDto {
  /** @format int32 */
  start?: number;
  /** @format int32 */
  size?: number;
}

export interface BaseResponseListSaSession {
  /** @format int32 */
  code?: number;
  message?: string;
  data?: SaSession[];
}

export interface SaSession {
  id?: string;
  /** @format int64 */
  createTime?: number;
  dataMap?: Record<string, object>;
  tokenSignList?: TokenSign[];
  /** @format int64 */
  timeout?: number;
}

export interface TokenSign {
  value?: string;
  device?: string;
}

export interface RolePermissionDto {
  roleId?: string;
  permissionIds?: string[];
}

export interface BaseResponseListPermission {
  /** @format int32 */
  code?: number;
  message?: string;
  data?: Permission[];
}

export interface Permission {
  id?: string;
  pid?: string;
  name?: string;
  value?: string;
  /** @format int32 */
  status?: number;
}

export interface BaseResponseLinkedHashMapStringObject {
  /** @format int32 */
  code?: number;
  message?: string;
  data?: Record<string, object>;
}
