/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import type {BaseResponseString, BaseResponseUser, UserLoginDto} from '../models';
import {STABaseService, STAHttpOptions} from '../_base.service';

@Injectable({providedIn: 'root'})
export class 用户登录Service extends STABaseService {
  /**
   * 修改密码
   *
   * @request POST:/user/updatePass
   */
  updatePass(req: UserLoginDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/updatePass`, {
      body: req,
      ...options
    });
  }

  /**
   * 登录
   *
   * @request POST:/user/doLogin
   */
  doLogin(req: UserLoginDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/doLogin`, {
      body: req,
      ...options
    });
  }

  /**
   * 不记住我登录
   *
   * @request POST:/user/doLogin1
   */
  doLogin1(req: UserLoginDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/doLogin1`, {
      body: req,
      ...options
    });
  }

  /**
   * 注销登录
   *
   * @request GET:/user/logout
   */
  logout1(options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('GET', `/user/logout`, {
      ...options
    });
  }

  /**
   * 查询登录状态
   *
   * @request GET:/user/isLogin
   */
  isLogin(options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('GET', `/user/isLogin`, {
      ...options
    });
  }

  /**
   * 获取用户信息
   *
   * @request GET:/user/getUserInfo
   */
  getUserInfo(options?: STAHttpOptions): Observable<BaseResponseUser> {
    return this.request('GET', `/user/getUserInfo`, {
      ...options
    });
  }

  /**
   * 获取公钥
   *
   * @request GET:/user/getPublicKey
   */
  getPublicKey(options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('GET', `/user/getPublicKey`, {
      ...options
    });
  }

  /**
   * 获取当前会话id
   *
   * @request GET:/user/getLoginIdAsString
   */
  getLoginIdAsString(options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('GET', `/user/getLoginIdAsString`, {
      ...options
    });
  }

  /**
   * 检验当前会话是否已经登录
   *
   * @request GET:/user/checkLogin
   */
  checkLogin(options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('GET', `/user/checkLogin`, {
      ...options
    });
  }
}
