/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import type {BaseResponseString, DisableAccountDto} from '../models';
import {STABaseService, STAHttpOptions} from '../_base.service';
import type {DisableUntieDisableRequest} from './dtos';

@Injectable({providedIn: 'root'})
export class DisableService extends STABaseService {
  /**
   * 解封指定账号
   *
   * @request POST:/disable/untieDisable
   */
  untieDisable(req: DisableUntieDisableRequest, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/disable/untieDisable`, {
      params: req,
      ...options
    });
  }

  /**
   * 封禁指定账号
   *
   * @request POST:/disable/disable
   */
  disable(req: DisableAccountDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/disable/disable`, {
      body: req,
      ...options
    });
  }
}
