/* eslint-disable */

/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

export interface 角色管理Delete1Request {
  id: string;
}

export interface 角色管理ListPermissionRequest {
  roleId: string;
}
