/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import type {BaseResponseLinkedHashMapStringObject} from '../models';
import {STABaseService, STAHttpOptions} from '../_base.service';

@Injectable({providedIn: 'root'})
export class 权限认证Service extends STABaseService {
  /**
   * 查询权限
   *
   * @request GET:/jur/getPermission
   */
  getPermission(options?: STAHttpOptions): Observable<BaseResponseLinkedHashMapStringObject> {
    return this.request('GET', `/jur/getPermission`, {
      ...options
    });
  }
}
