/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import type {JwtDto} from '../models';

export interface UserGetUserInfoByUsernameRequest {
  username: string;
}

export interface UserGetUserInfoByUserIdRequest {
  userId: string;
}

export interface UserGetRoleListByUserIdRequest {
  userId: string;
}

export interface UserGetJwtRequest {
  jwtDto: JwtDto;
}

export interface UserGenerateJwtRequest {
  jwtDto: JwtDto;
}

export interface UserDeleteRequest {
  id: string;
}
