/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import type {
  BaseResponseListRole,
  BaseResponsePageUser,
  BaseResponseString,
  BaseResponseUser,
  FindUserPageDto,
  RoleRelationDto,
  User,
  UserRegisterDto
} from '../models';
import {STABaseService, STAHttpOptions} from '../_base.service';
import type {
  UserDeleteRequest,
  UserGenerateJwtRequest,
  UserGetJwtRequest,
  UserGetRoleListByUserIdRequest,
  UserGetUserInfoByUserIdRequest,
  UserGetUserInfoByUsernameRequest
} from './dtos';

@Injectable({providedIn: 'root'})
export class UserService extends STABaseService {
  /**
   * 修改
   *
   * @request POST:/user/update
   */
  update(req: User, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/update`, {
      body: req,
      ...options
    });
  }

  /**
   * 添加
   *
   * @request POST:/user/save
   */
  save(req: UserRegisterDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/save`, {
      body: req,
      ...options
    });
  }

  /**
   * 保存授权角色
   *
   * @request POST:/user/saveAuthRole
   */
  saveAuthRole(req: RoleRelationDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/saveAuthRole`, {
      body: req,
      ...options
    });
  }

  /**
   * 用户查询
   *
   * @request POST:/user/list
   */
  list(req: FindUserPageDto, options?: STAHttpOptions): Observable<BaseResponsePageUser> {
    return this.request('POST', `/user/list`, {
      body: req,
      ...options
    });
  }

  /**
   * 根据用户名获取用户信息
   *
   * @request POST:/user/getUserInfoByUsername
   */
  getUserInfoByUsername(req: UserGetUserInfoByUsernameRequest, options?: STAHttpOptions): Observable<BaseResponseUser> {
    return this.request('POST', `/user/getUserInfoByUsername`, {
      params: req,
      ...options
    });
  }

  /**
   * 根据用户Id获取用户信息
   *
   * @request POST:/user/getUserInfoByUserId
   */
  getUserInfoByUserId(req: UserGetUserInfoByUserIdRequest, options?: STAHttpOptions): Observable<BaseResponseUser> {
    return this.request('POST', `/user/getUserInfoByUserId`, {
      params: req,
      ...options
    });
  }

  /**
   * 获取用户的角色列表
   *
   * @request POST:/user/getRoleListByUserId
   */
  getRoleListByUserId(req: UserGetRoleListByUserIdRequest, options?: STAHttpOptions): Observable<BaseResponseListRole> {
    return this.request('POST', `/user/getRoleListByUserId`, {
      params: req,
      ...options
    });
  }

  /**
   * 得到Jwt
   *
   * @request POST:/user/getJwt
   */
  getJwt(req: UserGetJwtRequest, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/getJwt`, {
      params: req,
      ...options
    });
  }

  /**
   * 生成Jwt
   *
   * @request POST:/user/generateJwt
   */
  generateJwt(req: UserGenerateJwtRequest, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/generateJwt`, {
      params: req,
      ...options
    });
  }

  /**
   * 删除
   *
   * @request POST:/user/delete
   */
  delete(req: UserDeleteRequest, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/delete`, {
      params: req,
      ...options
    });
  }

  /**
   * 获取登录用户信息
   *
   * @request GET:/user/getLoginUserInfo
   */
  getLoginUserInfo(options?: STAHttpOptions): Observable<BaseResponseUser> {
    return this.request('GET', `/user/getLoginUserInfo`, {
      ...options
    });
  }
}
