/*
* Automatically generated by 'ng g ng-alain:plugin icon'
*/

import {
  FullscreenExitOutline,
  FullscreenOutline,
  LockOutline,
  LogoutOutline,
  SettingOutline,
  ToolOutline,
  UserOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  FullscreenExitOutline,
  FullscreenOutline,
  LockOutline,
  LogoutOutline,
  SettingOutline,
  ToolOutline,
  UserOutline
];
