/* eslint-disable */

/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

export interface 用户管理GetUserInfoByUsernameRequest {
  username: string;
}

export interface 用户管理GetRoleListByUserIdRequest {
  userId: string;
}

export interface 用户管理DeleteRequest {
  id: string;
}
