/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import type {
  BaseResponseListRole,
  BaseResponseObject,
  BaseResponseString,
  BaseResponseUser,
  FindPageDto,
  RoleRelationDto,
  User,
  UserRegisterDto
} from '../models';
import {STABaseService, STAHttpOptions} from '../_base.service';
import type {
  用户管理DeleteRequest,
  用户管理GetRoleListByUserIdRequest,
  用户管理GetUserInfoByUsernameRequest
} from './dtos';

@Injectable({providedIn: 'root'})
export class 用户管理Service extends STABaseService {
  /**
   * 修改
   *
   * @request POST:/user/update
   */
  update(req: User, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/update`, {
      body: req,
      ...options
    });
  }

  /**
   * 添加
   *
   * @request POST:/user/save
   */
  save(req: UserRegisterDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/save`, {
      body: req,
      ...options
    });
  }

  /**
   * 保存授权角色
   *
   * @request POST:/user/saveAuthRole
   */
  saveAuthRole(req: RoleRelationDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/saveAuthRole`, {
      body: req,
      ...options
    });
  }

  /**
   * 用户查询
   *
   * @request POST:/user/pageList
   */
  pageList(req: FindPageDto, options?: STAHttpOptions): Observable<BaseResponseObject> {
    return this.request('POST', `/user/pageList`, {
      body: req,
      ...options
    });
  }

  /**
   * 用户查询-角色
   *
   * @request POST:/user/pageListByRoleId
   */
  pageListByRoleId(req: FindPageDto, options?: STAHttpOptions): Observable<BaseResponseObject> {
    return this.request('POST', `/user/pageListByRoleId`, {
      body: req,
      ...options
    });
  }

  /**
   * 根据用户名获取用户信息
   *
   * @request POST:/user/getUserInfoByUsername
   */
  getUserInfoByUsername(req: 用户管理GetUserInfoByUsernameRequest, options?: STAHttpOptions): Observable<BaseResponseUser> {
    return this.request('POST', `/user/getUserInfoByUsername`, {
      params: req,
      ...options
    });
  }

  /**
   * 获取用户的角色列表
   *
   * @request POST:/user/getRoleListByUserId
   */
  getRoleListByUserId(req: 用户管理GetRoleListByUserIdRequest, options?: STAHttpOptions): Observable<BaseResponseListRole> {
    return this.request('POST', `/user/getRoleListByUserId`, {
      params: req,
      ...options
    });
  }

  /**
   * 删除
   *
   * @request POST:/user/delete
   */
  delete(req: 用户管理DeleteRequest, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/user/delete`, {
      params: req,
      ...options
    });
  }
}
