/* eslint-disable */
/*
 * Automatically generated by 'ng g ng-alain:sta'
 * @see https://ng-alain.com/cli/sta
 *
 * Inspired by: https://github.com/acacode/swagger-typescript-api
 */

import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import type {BaseResponseString, UserLoginDto} from '../models';
import {STABaseService, STAHttpOptions} from '../_base.service';

@Injectable({providedIn: 'root'})
export class LoginService extends STABaseService {
  /**
   * 修改密码
   *
   * @request POST:/login/updatePassword
   */
  updatePassword(req: UserLoginDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/login/updatePassword`, {
      body: req,
      ...options
    });
  }

  /**
   * 登录
   *
   * @request POST:/login/doLogin
   */
  doLogin(req: UserLoginDto, options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('POST', `/login/doLogin`, {
      body: req,
      ...options
    });
  }

  /**
   * 注销登录
   *
   * @request GET:/login/logout
   */
  logout1(options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('GET', `/login/logout`, {
      ...options
    });
  }

  /**
   * 查询登录状态
   *
   * @request GET:/login/isLogin
   */
  isLogin(options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('GET', `/login/isLogin`, {
      ...options
    });
  }

  /**
   * 获取当前会话id
   *
   * @request GET:/login/getLoginIdAsString
   */
  getLoginIdAsString(options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('GET', `/login/getLoginIdAsString`, {
      ...options
    });
  }

  /**
   * 检验当前会话是否已经登录
   *
   * @request GET:/login/checkLogin
   */
  checkLogin(options?: STAHttpOptions): Observable<BaseResponseString> {
    return this.request('GET', `/login/checkLogin`, {
      ...options
    });
  }
}
